export const speakLanguages = [
    { language: "US English", code: "en-US" },
    { language: "UK English", code: "en-GB" },
    { language: "Deutsch", code: "de-DE" },
    { language: "español", code: "es-ES" },
    { language: "español de Estados Unidos", code: "es-US" },
    { language: "français", code: "fr-FR" },
    { language: "हिन्दी Hindi", code: "hi-IN" },
    { language: "Bahasa Indonesia", code: "id-ID" },
    { language: "italiano", code: "it-IT" },
    { language: "日本語", code: "ja-JP" },
    { language: "한국의", code: "ko-KR" },
    { language: "Nederlands", code: "nl-NL" },
    { language: "polski", code: "pl-PL" },
    { language: "português do Brasil", code: "pt-BR" },
    { language: "русский", code: "ru-RU" },
    { language: "普通话（中国大陆）", code: "zh-CN" },
    { language: "粤語（香港）", code: "zh-HK" },
    { language: "國語（臺灣）", code: "zh-TW" }
];